In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [45]:
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [47]:
df.species.value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [48]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [49]:
df['species'] = df['species'].map({'setosa':0,'versicolor':1,'virginica':2})

In [50]:
X = df.drop(['species'],axis=1)
y = df['species']

In [51]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [52]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [53]:
from sklearn.model_selection import train_test_split

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [55]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
96            5.7          2.9           4.2          1.3
105           7.6          3.0           6.6          2.1
66            5.6          3.0           4.5          1.5
0             5.1          3.5           1.4          0.2
122           7.7          2.8           6.7          2.0

In [56]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
73            6.1          2.8           4.7          1.2
18            5.7          3.8           1.7          0.3
118           7.7          2.6           6.9          2.3
78            6.0          2.9           4.5          1.5
76            6.8          2.8           4.8          1.4

In [57]:
y_train.head()

96     1
105    2
66     1
0      0
122    2
Name: species, dtype: int64

In [58]:
y_test.head()

73     1
18     0
118    2
78     1
76     1
Name: species, dtype: int64

In [59]:
from sklearn.tree import DecisionTreeClassifier

In [60]:

reg = DecisionTreeClassifier(criterion='entropy')
reg.fit(X_train,y_train)



DecisionTreeClassifier(criterion='entropy')

In [61]:
y_train_pred = reg.predict(X_train)

In [62]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [63]:
y_train[:10]

C:\Users\korla\AppData\Local\Temp\ipykernel_40232\891270224.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  y_train[:10]


96     1
105    2
66     1
0      0
122    2
67     1
28     0
40     0
44     0
60     1
Name: species, dtype: int64

In [64]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [65]:
accuracy_score(y_train,y_train_pred)

1.0

In [66]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        35
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100



In [67]:
confusion_matrix(y_train,y_train_pred)

array([[31,  0,  0],
       [ 0, 35,  0],
       [ 0,  0, 34]], dtype=int64)

In [68]:
y_test_pred = reg.predict(X_test)
y_test_pred[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [69]:
y_test[:10]

C:\Users\korla\AppData\Local\Temp\ipykernel_40232\2588316582.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  y_test[:10]


73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
Name: species, dtype: int64

In [70]:
accuracy_score(y_test,y_test_pred)

0.98

In [71]:
confusion_matrix(y_test,y_test_pred)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 15]], dtype=int64)

In [72]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      1.00      0.97        15
           2       1.00      0.94      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



- Limitation of Decision Tree 
- If data is more it follows overfitting problem 
- To overcome the overfitting problem use Random Forest 

## Adaboost 

In [76]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
reg = AdaBoostClassifier(base_estimator=log , n_estimators=100 , learning_rate=1.0)



In [77]:
reg.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=LogisticRegression(), n_estimators=100)

In [78]:
reg.score(X_train,y_train)

0.94

In [79]:
reg.score(X_test,y_test)

0.94

In [56]:
# lets check with the hypeparameter tuning technique using GridsearchCV

### GridsearchCV

In [40]:
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [42]:
model = DecisionTreeClassifier()


In [59]:
parameters = {
    
    'criterion':['gini','entropy'],
    'max_depth':[2,3,4,5,6,7,10,11,14,20,25,30],
    'min_samples_split':[2,3,4,5,6],
    'min_samples_leaf':[2,3,4,5],
    'class_weight':['balanced',None]
    }


grid_model = GridSearchCV(estimator=model,
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=10)

grid_model1 = grid_model.fit(X_train,y_train)

In [60]:
grid_model1.best_params_

{'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': 4,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'presort': True}

In [64]:
reg1 = DecisionTreeClassifier(class_weight='balanced',criterion='gini',max_depth=4,min_samples_leaf=3,
                              min_samples_split=2,presort=True)
reg1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight='balanced', criterion='gini', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=True,
                       random_state=None, splitter='best')

In [68]:
y_train_pred1 = reg1.predict(X_train)
y_train_pred1[:10]


array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [69]:
y_train_pred[:10]

array([1, 2, 1, 0, 2, 1, 0, 0, 0, 1], dtype=int64)

In [70]:
accuracy_score(y_train,y_train_pred1)

0.96

In [71]:
confusion_matrix(y_train,y_train_pred1)

array([[31,  0,  0],
       [ 0, 32,  3],
       [ 0,  1, 33]], dtype=int64)

In [72]:
print(classification_report(y_train,y_train_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       0.97      0.91      0.94        35
           2       0.92      0.97      0.94        34

    accuracy                           0.96       100
   macro avg       0.96      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100



In [73]:
y_test_pred1 = reg1.predict(X_test)

In [74]:
y_test_pred1[:10]

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1], dtype=int64)

In [75]:
accuracy_score(y_test,y_test_pred1)

1.0

In [76]:
confusion_matrix(y_test,y_test_pred1)

array([[19,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 16]], dtype=int64)

In [77]:
print(classification_report(y_test,y_test_pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        16

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50

